apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-rule-engine-config
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  APP_RULES_HIGH_VALUE_THRESHOLD: "50000"
  APP_RULES_VELOCITY_WINDOW_SECONDS: "60"
  APP_RULES_VELOCITY_MAX_TRANSACTIONS: "5"
  APP_RULES_UNUSUAL_HOURS_START: "23"
  APP_RULES_UNUSUAL_HOURS_END: "5"
  APP_RULES_ROUND_AMOUNT_THRESHOLD: "10000"
  TZ: "Africa/Johannesburg"
